In [15]:
import pandas as pd
import numpy as np
import requests
import os
import json

In [18]:
with open('../apiKeys/apiKeys.json') as f:
    API_KEYS = json.load(f)
    f.close()

In [19]:
AEROAPI_BASE_URL = "https://aeroapi.flightaware.com/aeroapi"

def get_operator_flights(operator_id: str) -> dict:
    url = f"{AEROAPI_BASE_URL}/operators/{operator_id}/flights"
    headers = {"x-apikey": API_KEYS['FA_API_KEY']}
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    return response.json()

# Example usage:
data = pd.DataFrame()
for airline in ["UAL", "AAL", "DL"]:
    flights = get_operator_flights(airline)
    flights_df = pd.DataFrame(flights["scheduled"])
    flights_df.to_csv(f"data/{airline}_flights.csv")
    data = pd.concat([data, flights_df])
data

/var/folders/mh/b5m2p8fd04x2knz5_hwd1rqw0000gn/T/ipykernel_40169/4257495791.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, flights_df])

,ident,ident_icao,ident_iata,actual_runway_off,actual_runway_on,fa_flight_id,operator,operator_icao,operator_iata,flight_number,...,route,baggage_claim,seats_cabin_business,seats_cabin_coach,seats_cabin_first,gate_origin,gate_destination,terminal_origin,terminal_destination,type
0,UAL1286,UAL1286,UA1286,None,None,UAL1286-1778285000-fa-811p,UAL,UAL,UA,1286,...,GOPUP4 HOCKE FNT WYNDE3,None,NaN,NaN,12.0,F98,B22,1,1,Airline
1,UAL1322,UAL1322,UA1322,None,None,UAL1322-1778285099-fa-1569p,UAL,UAL,UA,1322,...,JDUBB4 MELTN ALDAN4,None,NaN,NaN,12.0,D2,D17,None,2,Airline
2,UAL1130,UAL1130,UA1130,None,None,UAL1130-1778306240-fa-746p,UAL,UAL,UA,1130,...,RELTA UA758 ENALO UL207 NALDA UL207 MUVAP VIKM...,None,NaN,NaN,NaN,None,None,None,None,Airline
3,UAL776,UAL776,UA776,None,None,UAL776-1778311835-airline-1380p,UAL,UAL,UA,776,...,RDSOX1 JFRYS WILON CAMJO JROSS Q87 ALWZZ OGRAE...,None,NaN,NaN,20.0,46,C98,B,C,Airline
4,UAL2339,UAL2339,UA2339,None,None,UAL2339-1778285036-fa-275p,UAL,UAL,UA,2339,...,DANLS4 DANLS LITTR Q33 SWEUP GESNR2,None,NaN,NaN,20.0,B8,C30,None,C,Airline
5,UAL929,UAL929,UA929,None,None,UAL929-1778300665-fa-1899p,UAL,UAL,UA,929,...,EBAKE WISMO POSTS PADDE SVM Q907 DERLO Q913 RA...,None,22.0,NaN,46.0,C21,None,1,2,Airline
6,UAL2002,UAL2002,UA2002,None,None,UAL2002-1778285039-fa-141p,UAL,UAL,UA,2002,...,TRUKN2 SYRAH JSICA Q130 ROCCY KD42Q KA36S WARR...,None,NaN,NaN,NaN,E10,C39,3,C,Airline
7,UAL52,UAL52,UA52,None,None,UAL52-1778313401-airline-254p,UAL,UAL,UA,52,...,JCOBY4 SWANN BROSS Q419 RBV Q22 FOXWD WITCH AL...,None,24.0,NaN,30.0,D3,None,None,None,Airline
8,UAL517,UAL517,UA517,None,None,UAL517-1778285001-fa-515p,UAL,UAL,UA,517,...,MCMAN Q62 WATSN WATSN4,None,NaN,NaN,NaN,None,None,None,None,Airline
9,UAL2618,UAL2618,UA2618,None,None,UAL2618-1778285128-fa-1512p,UAL,UAL,UA,2618,...,CMSKY CARYN CYBIL PXV HITMN Q19 BULZI Q81 NICK...,None,NaN,NaN,NaN,None,None,None,None,Airline
10,UAL422,UAL422,UA422,None,None,UAL422-1778303027-fa-69p,UAL,UAL,UA,422,...,EBAKE WISMO POSTS PADDE SVM Q907 SIKBO MIVOK Q...,None,21.0,NaN,44.0,C18,None,1,None,Airline
11,UAL404,UAL404,UA404,None,None,UAL404-1778285035-fa-346p,UAL,UAL,UA,404,...,SNIDR2 WEMAR HTOWN3,None,NaN,NaN,12.0,B5,C30,B,C,Airline
12,UAL990,UAL990,UA990,None,None,UAL990-1778283410-fa-2027p,UAL,UAL,UA,990,...,SNTNA2 ORRCA FMG J94 LLC TWF BIL MOT 5000N/097...,None,24.0,NaN,50.0,G6,None,I,1,Airline
13,UAL1206,UAL1206,UA1206,None,None,UAL1206-1778296365-fa-1139p,UAL,UAL,UA,1206,...,BAYPO2 CAMJO Q99 SHIRY Q99 QUART PHLBO4,None,NaN,NaN,20.0,A7,A14,None,A,Airline
14,UAL1684,UAL1684,UA1684,None,None,UAL1684-1778285089-fa-662p,UAL,UAL,UA,1684,...,LURIC8 ORRTH CRAMM Q32 SWAPP Q34 RBV Q419 JFK ...,None,NaN,NaN,NaN,E8,B25,E,B,Airline
0,AAL302,AAL302,AA302,None,None,AAL302-1778308495-airline-1294p,AAL,AAL,AA,302,...,RBV Q430 SAAME BRNAN Q42 HIDON APE CREEP TTH M...,None,NaN,NaN,NaN,34,46B,8,4,Airline
1,AAL1003,AAL1003,AA1003,None,None,AAL1003-1778308998-airline-1662p,AAL,AAL,AA,1003,...,PEKUE PIGGG QUANE CARET BULET RUDDH3,None,NaN,NaN,NaN,H10,A3,3,None,Airline
2,AAL2278,AAL2278,AA2278,None,None,AAL2278-1778313421-airline-1394p,AAL,AAL,AA,2278,...,EBAKE WISMO POSTS PADDE SVM DKK PONCT JFUND2,None,NaN,NaN,NaN,H16,B17,3,B,Airline
3,AAL2828,AAL2828,AA2828,None,None,AAL2828-1778308495-airline-1045p,AAL,AAL,AA,2828,...,HURCN4 SMELZ Q116 JAWJA MGMRY SARKK YUYUN BERE...,None,NaN,NaN,NaN,D9,B7,None,B,Airline
4,AAL1323,AAL1323,AA1323,None,None,AAL1323-1778311646-airline-1481p,AAL,AAL,AA,1323,...,ZZOOO4 GBN ITEMM ITUCO Q2 EWM CAVRN INK UGABE ...,None,NaN,NaN,NaN,27,D44,2,None,Airline
5,AAL1922,AAL1922,AA1922,None,None,AAL1922-1778306904-airline-1257p,AAL,AAL,AA,1922,...,ALTNN2 DUCEN Q87 TAALN Q87 JROSS JOHAR Q109 DF...,None,NaN,NaN,NaN,D4,45,None,8,Airline
6,AAL1292,AAL1292,AA1292,None,None,AAL1292-1778311646-airline-1448p,AAL,AAL,AA,1292,...,NIITZ4 HOCEE TBC ACH TXO TURKI JOVEM6,None,NaN,NaN,NaN,D10,C22,1,C,Airline
7,AAL1513,AAL1513,AA1513,None,None,AAL1513-1778311646-airline-1686p,AAL,AAL,AA,1513,...,KLADA2 BITAC Y290 HAGIT Y421 HARBG L452 MUNOZ ...,None,NaN,NaN,NaN,E4,4,None,None,Airline
8,AAL2328,AAL2328,AA2328,None,None,AAL2328-1778313421-airline-1458p,AAL,AAL,AA,2328,...,ESTRR5 IPTAY CHOPZ THRSR ZJAYX GRNCH5,None,NaN,NaN,NaN,C9,50,None,B,Airline
9,AAL2348,AAL2348,AA2348,None,None,AAL2348-1778313421-airline-1488p,AAL,AAL,AA,2348,...,GOETZ7 DIYAB SYI TAZZA FILPZ4,None,NaN,NaN,NaN,4,A7,None,None,Airline
10,AAL2402,AAL2402,AA2402,None,None,AAL2402-1778313421-airline-1581p,AAL,AAL,AA,2402,...,HURCN4 KPASA Q118 THRSR SWFFT3,None,NaN,NaN,NaN,D41,C19,None,None,Airline
11,AAL1074,AAL1074,AA1074,None,None,AAL1074-1778311646-airline-1219p,AAL,AAL,AA,1074,...,FOLZZ3 ALYRA GRUBR Y299 SEELO WAALT Q131 PRONI...,None,NaN,NaN,NaN,D51,B15,None,B,Airline
12,AAL3220,AAL3220,AA3220,None,None,AAL3220-1778305036-airline-1631p,AAL,AAL,AA,3220,...,PATSS7 PATSS NELIE Q75 GVE AIROW CHSLY6,None,NaN,NaN,NaN,B20,B14,B,None,Airline
13,AAL1322,AAL1322,AA1322,None,None,AAL1322-1778311646-airline-1480p,AAL,AAL,AA,1322,...,LOWGN8 ROLLS TOTOE HALEN NIIXX4,None,NaN,NaN,NaN,D31,C32,D,None,Airline
14,AAL2688,AAL2688,AA2688,None,None,AAL2688-1778308495-airline-861p,AAL,AAL,AA,2688,...,CSHEL8 VIYAP Q87 JROSS Q135 RREGG Q117 SAWED Q...,None,NaN,NaN,NaN,D1,C19,None,C,Airline
0,DAL9961,DAL9961,DL9961,None,None,DAL9961-1778479805-fa-1385p,DAL,DAL,DL,9961,...,None,None,NaN,NaN,NaN,None,None,None,None,Airline
1,DAL642,DAL642,DL642,None,None,DAL642-1778299953-fa-9p,DAL,DAL,DL,642,...,CVM UJ41 TALBI UJ41 MATUR UJ41 NLD DLF INK J15...,None,NaN,NaN,NaN,59,A15,2,None,Airline
2,DAL709,DAL709,DL709,None,None,DAL709-1778300687-fa-403p,DAL,DAL,DL,709,...,RBV Q430 AIR CVG FAM TWRAY VINTA KK39E KK36C N...,None,NaN,NaN,NaN,None,None,None,None,Airline
3,DAL771,DAL771,DL771,None,None,DAL771-1778300171-fa-1251p,DAL,DAL,DL,771,...,RBV Q430 AIR J80 MCI J24 SLN J102 ALS J44 RSK ...,None,NaN,NaN,NaN,B28,25A,4,2,Airline
4,DAL798,DAL798,DL798,None,None,DAL798-1778300716-fa-496p,DAL,DAL,DL,798,...,RBV Q430 AIR J110 STL BUM ICT TOTOE FTI J244 Z...,None,20.0,149.0,NaN,A14,F7,4,3,Airline
5,DAL630,DAL630,DL630,None,None,DAL630-1778300728-fa-190p,DAL,DAL,DL,630,...,PILNA AXASA J93 ASUTA AMMOR OLAAA2,None,20.0,172.0,NaN,58,206,2,B,Airline
6,DAL2172,DAL2172,DL2172,None,None,DAL2172-1778299933-fa-8p,DAL,DAL,DL,2172,...,ZZOOO4 MTBAL EED J236 TBC HBU DANDD KD60Y ZIRK...,None,NaN,NaN,NaN,47,A6,2,M,Airline
7,DAL9960,DAL9960,DL9960,None,None,DAL9960-1778315697-fa-3822p,DAL,DAL,DL,9960,...,None,None,NaN,NaN,NaN,None,327,None,None,Airline
8,DAL3120,DAL3120,DL3120,None,None,DAL3120-1778300282-fa-2542p,DAL,DAL,DL,3120,...,VARNM2 RESPE IIU HAGAL GIIBS4,None,NaN,NaN,NaN,B27,A6,S,None,Airline
9,DAL2421,DAL2421,DL2421,None,None,DAL2421-1778300002-fa-437p,DAL,DAL,DL,2421,...,RUGGD3 PERTY CHE GLL MCK TOP ANX KAYLA3,None,NaN,NaN,NaN,None,None,None,None,Airline
10,DAL462,DAL462,DL462,None,None,DAL462-1778300643-fa-92p,DAL,DAL,DL,462,...,RDSOX1 JFRYS PATOY Q116 JAWJA CABLO MERDN TXK ...,None,20.0,173.0,NaN,71,28,B,2,Airline
11,DAL2468,DAL2468,DL2468,None,None,DAL2468-1778300306-fa-123p,DAL,DAL,DL,2468,...,GOPUP4 SLLAP ZATON KP78I KATES NARLY KD69Y FRO...,None,16.0,126.0,NaN,A12,B25,3,None,Airline
12,DAL841,DAL841,DL841,None,None,DAL841-1778300445-fa-235p,DAL,DAL,DL,841,...,ARCHZ1 WINEN LAKRR HAKMN ANJLL4,None,NaN,NaN,NaN,A22,36,None,3,Airline
13,DAL1346,DAL1346,DL1346,None,None,DAL1346-1778300756-fa-930p,DAL,DAL,DL,1346,...,PHIIL3 HRTWL Q54 NUTZE KOHLS1,None,20.0,179.0,NaN,B3,B24,S,None,Airline
14,DAL1668,DAL1668,DL1668,None,None,DAL1668-1778299993-fa-2p,DAL,DAL,DL,1668,...,KAYLN3 SMUUV WYNDE3,None,NaN,NaN,NaN,A7,M11,M,5,Airline

In [21]:
data[data['operator_iata'] == 'UA']

,ident,ident_icao,ident_iata,actual_runway_off,actual_runway_on,fa_flight_id,operator,operator_icao,operator_iata,flight_number,...,route,baggage_claim,seats_cabin_business,seats_cabin_coach,seats_cabin_first,gate_origin,gate_destination,terminal_origin,terminal_destination,type
0,UAL1286,UAL1286,UA1286,None,None,UAL1286-1778285000-fa-811p,UAL,UAL,UA,1286,...,GOPUP4 HOCKE FNT WYNDE3,None,NaN,NaN,12.0,F98,B22,1,1,Airline
1,UAL1322,UAL1322,UA1322,None,None,UAL1322-1778285099-fa-1569p,UAL,UAL,UA,1322,...,JDUBB4 MELTN ALDAN4,None,NaN,NaN,12.0,D2,D17,None,2,Airline
2,UAL1130,UAL1130,UA1130,None,None,UAL1130-1778306240-fa-746p,UAL,UAL,UA,1130,...,RELTA UA758 ENALO UL207 NALDA UL207 MUVAP VIKM...,None,NaN,NaN,NaN,None,None,None,None,Airline
3,UAL776,UAL776,UA776,None,None,UAL776-1778311835-airline-1380p,UAL,UAL,UA,776,...,RDSOX1 JFRYS WILON CAMJO JROSS Q87 ALWZZ OGRAE...,None,NaN,NaN,20.0,46,C98,B,C,Airline
4,UAL2339,UAL2339,UA2339,None,None,UAL2339-1778285036-fa-275p,UAL,UAL,UA,2339,...,DANLS4 DANLS LITTR Q33 SWEUP GESNR2,None,NaN,NaN,20.0,B8,C30,None,C,Airline
5,UAL929,UAL929,UA929,None,None,UAL929-1778300665-fa-1899p,UAL,UAL,UA,929,...,EBAKE WISMO POSTS PADDE SVM Q907 DERLO Q913 RA...,None,22.0,NaN,46.0,C21,None,1,2,Airline
6,UAL2002,UAL2002,UA2002,None,None,UAL2002-1778285039-fa-141p,UAL,UAL,UA,2002,...,TRUKN2 SYRAH JSICA Q130 ROCCY KD42Q KA36S WARR...,None,NaN,NaN,NaN,E10,C39,3,C,Airline
7,UAL52,UAL52,UA52,None,None,UAL52-1778313401-airline-254p,UAL,UAL,UA,52,...,JCOBY4 SWANN BROSS Q419 RBV Q22 FOXWD WITCH AL...,None,24.0,NaN,30.0,D3,None,None,None,Airline
8,UAL517,UAL517,UA517,None,None,UAL517-1778285001-fa-515p,UAL,UAL,UA,517,...,MCMAN Q62 WATSN WATSN4,None,NaN,NaN,NaN,None,None,None,None,Airline
9,UAL2618,UAL2618,UA2618,None,None,UAL2618-1778285128-fa-1512p,UAL,UAL,UA,2618,...,CMSKY CARYN CYBIL PXV HITMN Q19 BULZI Q81 NICK...,None,NaN,NaN,NaN,None,None,None,None,Airline
10,UAL422,UAL422,UA422,None,None,UAL422-1778303027-fa-69p,UAL,UAL,UA,422,...,EBAKE WISMO POSTS PADDE SVM Q907 SIKBO MIVOK Q...,None,21.0,NaN,44.0,C18,None,1,None,Airline
11,UAL404,UAL404,UA404,None,None,UAL404-1778285035-fa-346p,UAL,UAL,UA,404,...,SNIDR2 WEMAR HTOWN3,None,NaN,NaN,12.0,B5,C30,B,C,Airline
12,UAL990,UAL990,UA990,None,None,UAL990-1778283410-fa-2027p,UAL,UAL,UA,990,...,SNTNA2 ORRCA FMG J94 LLC TWF BIL MOT 5000N/097...,None,24.0,NaN,50.0,G6,None,I,1,Airline
13,UAL1206,UAL1206,UA1206,None,None,UAL1206-1778296365-fa-1139p,UAL,UAL,UA,1206,...,BAYPO2 CAMJO Q99 SHIRY Q99 QUART PHLBO4,None,NaN,NaN,20.0,A7,A14,None,A,Airline
14,UAL1684,UAL1684,UA1684,None,None,UAL1684-1778285089-fa-662p,UAL,UAL,UA,1684,...,LURIC8 ORRTH CRAMM Q32 SWAPP Q34 RBV Q419 JFK ...,None,NaN,NaN,NaN,E8,B25,E,B,Airline